version: '3.4'

services:
  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  accountservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

