version: "3.4"

services:
  accountdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Str0ngPass!
    volumes:
      - ./volumes/AccountDB:/var/opt/mssql/data

  productdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1434:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Str0ngPass!
    volumes:
      - ./volumes/ProductDB:/var/opt/mssql/data

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1435:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Str0ngPass!
    volumes: 
      - ./volumes/OrderDB:/var/opt/mssql/data

  accountservice:
    image: accountservice
    restart: always
    ports:
      - 5000:80
    depends_on:
      - accountdb

  productservice:
    image: productservice
    restart: always
    ports:
      - 5001:80
    depends_on:
      - productdb

  orderservice:
    image: orderservice
    restart: always
    ports:
      - 5002:80

    depends_on:
      - orderdb